# Generated by Django 5.0.6 on 2024-06-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='circulating_supply',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='output',
            name='diluted_market_cap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='output',
            name='market_cap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='output',
            name='market_change',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='output',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='output',
            name='price_change',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='output',
            name='total_supply',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='output',
            name='volume',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='output',
            name='volume_change',
            field=models.CharField(max_length=100),
        ),
    ]
