# Generated by Django 5.0.6 on 2024-06-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_output_market_cap_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='market_cap_rank',
        ),
    ]
